#!/usr/bin/env node
/**
 * create-hybrid-app — assembles an offline-first project.
 *
 * Backend + offline core + a skin, pruned of its demo content and given an
 * identity of its own. The skin sources live outside this repository because
 * they are licensed; see templates/skins/<name>/skin.json.
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  assembleBackend,
  assembleCore,
  assembleFrontend,
  assembleInfra,
} from './lib/assemble.js';
import { drawIdentity } from './lib/differentiate.js';
import { listSkins, loadSkin } from './lib/skin.js';

const REPO_ROOT = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '..', '..');

function parseArgs(argv) {
  const args = { skin: 'minimal' };

  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;

    const [flag, inline] = token.slice(2).split('=');
    const value = inline ?? (argv[i + 1]?.startsWith('--') ? undefined : argv[++i]);

    if (flag === 'help') args.help = true;
    else if (flag === 'force') args.force = true;
    else args[flag] = value;
  }

  return args;
}

function usage() {
  return `
create-hybrid-app — offline-first project generator

  --name <name>      Project name (required)
  --skin <name>      Skin to build on (default: minimal)
  --out <dir>        Where to create it (default: ./<name>)
  --seed <text>      Identity seed (default: the project name)
  --force            Overwrite a non-empty target
  --help

Available skins: ${listSkins(REPO_ROOT).join(', ') || 'none'}

Licensed skins are not in this repository. Drop your own copy in
skins-src/<source path>; the skin manifest says which one it expects.
`.trimStart();
}

function canBind(port, host) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(false));
    server.once('listening', () => server.close(() => resolve(true)));
    server.listen(port, host);
  });
}

function isAnyoneListening(port) {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    const done = (answer) => {
      socket.destroy();
      resolve(answer);
    };

    socket.setTimeout(300);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
    socket.connect(port, '127.0.0.1');
  });
}

/**
 * Free on both addresses, and with nothing answering on it.
 *
 * Two quirks make a single probe unreliable. Windows does not refuse a bind to
 * 0.0.0.0 while something holds 127.0.0.1 on the same port, nor the reverse.
 * And Docker Desktop forwards published ports through a proxy that leaves them
 * bindable from Windows while a container is plainly serving on them -- only a
 * connection attempt sees that. A generated project that collides on its first
 * `up` is a poor introduction to a stack meant for awkward conditions.
 */
async function isPortFree(port) {
  if (await isAnyoneListening(port)) return false;
  return (await canBind(port, '0.0.0.0')) && (await canBind(port, '127.0.0.1'));
}

/**
 * Ports that are actually free on this machine.
 *
 * A generated project that collides with a native PostgreSQL on 5432 fails on
 * first run, which is a poor introduction to a stack whose whole point is
 * working in awkward conditions.
 */
async function choosePorts() {
  const wanted = { postgres: 5432, redis: 6379, django: 8000, next: 3000 };
  const chosen = {};

  for (const [service, preferred] of Object.entries(wanted)) {
    let port = preferred;
    while (!(await isPortFree(port))) port += 1;
    chosen[service] = port;
  }

  return chosen;
}

function makeSecrets() {
  const secret = () => crypto.randomBytes(24).toString('base64url');
  return {
    dbPassword: secret(),
    appDbPassword: secret(),
    secretKey: secret(),
    jwtKey: secret(),
  };
}

function projectReadme({ projectName, skin, identity, ports }) {
  return `# ${projectName}

Offline-first application generated by create-hybrid-app.

- **Skin:** ${skin.title ?? skin.name}
- **Palette:** ${identity.palette.label} (\`${identity.palette.primary}\` / \`${identity.palette.secondary}\`)
- **Shape:** ${identity.shape.id}${identity.layout ? `\n- **Layout:** ${identity.layout}` : ''}
- **Seed:** \`${identity.seed}\`

Rerunning the generator with the same seed reproduces this identity exactly.

## Run it

\`\`\`bash
COMPOSE="docker compose -f docker/docker-compose.yml --env-file .env"

$COMPOSE up -d --build
$COMPOSE exec django python manage.py migrate
$COMPOSE exec django python manage.py seed_demo
$COMPOSE exec django python manage.py test
\`\`\`

| Service | URL |
|---------|-----|
| Frontend | http://localhost:${ports.next} |
| API | http://localhost:${ports.django}/api/health/ |
| Admin | http://localhost:${ports.django}/admin/ |

Sign in as \`mor_user\` / \`demo1234\`.

## What isolates tenants

Row-level security, installed by \`backend/core/migrations/0002_rls_and_audit.py\`.
The application connects as \`hybrid_app\`, which is neither a superuser nor
\`BYPASSRLS\`; either would make every policy decorative. \`manage.py test\`
asserts this, so a misconfiguration fails the suite rather than leaking quietly.

## Adding a synced entity

1. A model in \`backend/core/models.py\`, plus a handler in \`_apply_event\`
   (\`backend/core/views.py\`) — it raises \`NotImplementedError\` by design for
   types it does not know.
2. A policy for the new table, in a migration. Nothing enforces this yet.
3. A store on the frontend: a type extending \`SyncedEntity\` and one call to
   \`createEntityStore\`. Versioning, tombstones and conflict-safe merging come
   from the core.
`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help || !args.name) {
    process.stdout.write(usage());
    process.exit(args.name ? 0 : 1);
  }

  const projectName = args.name;
  const targetDir = path.resolve(args.out ?? projectName);
  const seed = args.seed ?? projectName;

  if (fs.existsSync(targetDir) && fs.readdirSync(targetDir).length && !args.force) {
    throw new Error(`${targetDir} exists and is not empty. Pass --force to overwrite.`);
  }

  const skin = loadSkin(REPO_ROOT, args.skin);
  const identity = drawIdentity({
    seed,
    layouts: skin.layouts ?? [],
    assets: loadAssetManifest(REPO_ROOT),
  });

  const ports = await choosePorts();
  const secrets = makeSecrets();

  console.log(`\nAssembling ${projectName} on the ${skin.title ?? skin.name} skin`);
  console.log(`  identity  ${identity.palette.label}, ${identity.shape.id}${identity.layout ? `, ${identity.layout}` : ''}`);
  console.log(`  seed      ${seed}`);

  fs.mkdirSync(targetDir, { recursive: true });

  const backendFiles = assembleBackend({ repoRoot: REPO_ROOT, targetDir });
  const coreFiles = assembleCore({ repoRoot: REPO_ROOT, targetDir });
  const frontend = assembleFrontend({
    repoRoot: REPO_ROOT,
    skin,
    identity,
    projectName,
    targetDir,
  });
  assembleInfra({ repoRoot: REPO_ROOT, targetDir, projectName, ports, secrets });

  fs.writeFileSync(
    path.join(targetDir, 'README.md'),
    projectReadme({ projectName, skin, identity, ports }),
    'utf8',
  );

  console.log(`\n  backend   ${backendFiles} files`);
  console.log(`  core      ${coreFiles} files`);
  console.log(`  frontend  ${frontend.copied} copied, ${frontend.pruned} pruned, ${frontend.overlay} overlaid`);
  console.log(`  ports     postgres ${ports.postgres}, redis ${ports.redis}, api ${ports.django}, web ${ports.next}`);

  for (const warning of frontend.warnings) {
    console.log(`  warning   ${warning}`);
  }

  console.log(`\nDone. Next:\n  cd ${path.relative(process.cwd(), targetDir) || '.'}\n  docker compose -f docker/docker-compose.yml --env-file .env up -d --build\n`);
}

/**
 * The asset bank is optional and lives outside the repository.
 *
 * Without a manifest the generator still works; projects just share the stock
 * imagery their skin shipped with, which is the thing this is meant to avoid.
 */
function loadAssetManifest(repoRoot) {
  const manifestPath = path.join(repoRoot, 'assets-bank', 'assets.manifest.json');
  if (!fs.existsSync(manifestPath)) return [];

  try {
    return JSON.parse(fs.readFileSync(manifestPath, 'utf8')).assets ?? [];
  } catch (error) {
    console.log(`  warning   asset manifest unreadable: ${error.message}`);
    return [];
  }
}

main().catch((error) => {
  process.stderr.write(`\n${error.message}\n\n`);
  process.exit(1);
});
